more off;
load ourFunctionIn5.txt values;
layerSizes = [1 20 15 10];
eta = 0.1;
gValue = 1;
betaValue = 0.5;
error = 1;
momentum = 0.5;
etaAdaptativo = 5;
a = 0.05;
b = 0.1;
W = initializeWeights(layerSizes);
multiLayerPerceptron(W,values, layerSizes, eta, gValue, betaValue, error, momentum, etaAdaptativo, a, b);
