more off;
format long;
%load ourFunctionHomogenic.txt values;
x = -5 : 0.1 : 5;
y = sin(x) + 6 * (cos(x) .^ 2);
% y  = (sin(x) .* x.^3 + x/2);
% y = (sin(x) .* (x .^ 3) + x ./ 2);
y = y ./ max(abs(y));
values = [x' y'];
layerSizes = [1 25 10];
eta = 0.1;
gValue = 1;
betaValue = 0.75;
error = 1;
momentum = 0.5;
etaAdaptativo = 0;
a = 0.0005;
b = 0.1;
minimumDeltaError = 0;
noisePercentage = 0;
W = initializeWeights(layerSizes);
clf;
multiLayerPerceptron(W,values, layerSizes, eta, gValue, betaValue, error, momentum, etaAdaptativo, a, b, minimumDeltaError, noisePercentage);
